[[sources]]
organisation = "Cornell University College of Veterinary Medicine"
domain = "vet.cornell.edu"

[[sources]]
organisation = "Royal Veterinary College"
domain = "rvc.ac.uk"

[[sources]]
organisation = "MSD Veterinary Manual"
domain = "msdvetmanual.com"

[[sources]]
organisation = "ASPCA"
domain = "aspca.org"

[[sources]]
organisation = "PDSA"
domain = "pdsa.org.uk"

[[sources]]
organisation = "Blue Cross"
domain = "bluecross.org.uk"
